service: kairo-lite-api-products
frameworkVersion: '3'

plugins:
  - serverless-offline
custom:
  config: ../../envs/credentials.${self:provider.stage}.json

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'prod'}
  region: us-east-1
  environment:
    STAGE: ${file(${self:custom.config}):stage}
    FILE_ENVIRONMENT: ${file(${self:custom.config}):fileEnvironment}
    RUN_LIKE: ${file(${self:custom.config}):run_like}
    DATABASE_HOST: ${file(${self:custom.config}):dbHost}
    DATABASE_USER: ${file(${self:custom.config}):dbUser}
    DATABASE_NAME: ${file(${self:custom.config}):dbName}
    DATABASE_PASSWORD: ${file(${self:custom.config}):dbPassword}
    AWS_POOL_ID: ${file(${self:custom.config}):awsPoolId}

package:
  include:
    - ../libs/**
    - ../common/**
  exclude:
    - node_modules/**

functions:
  getProducts:
    handler: handler.read
    timeout: 30
    events:
      - http:
          path: products
          method: get
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  createProduct:
    handler: handler.create
    timeout: 30
    events:
      - http:
          path: products
          method: post
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  deleteProducts:
    handler: handler.delete
    timeout: 30
    events:
      - http:
          path: products
          method: delete
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}

  updateProduct:
    handler: handler.update
    timeout: 30
    events:
      - http:
          path: products
          method: put
          cors: true
    layers:
      - arn:${file(${self:custom.config}):layer}
